name: vod-strm-builder

services:
  vod-strm-builder:
    image: mars148/vod-strm-builder:latest
    container_name: vod-strm-builder
    ports:
      - "18080:8080"
    environment:
      VSB_WORK_DIR: /work
      PORT: "8080"
    volumes:
      - /opt/vod-strm-builder/work:/work
      - /mnt/strm/movies:/media/movies
      - /mnt/strm/tvshows:/media/tvshows
    restart: unless-stopped
